import type { LibraryItem, LibrarySource } from "@/lib/library-launch";
const acsm: LibrarySource={label:"ACSM — Resistance Training Guidelines Update, 2026",url:"https://acsm.org/resistance-training-guidelines-update-2026/"};
const cdcIntensity: LibrarySource={label:"CDC — How to Measure Physical Activity Intensity, 2025",url:"https://www.cdc.gov/physical-activity-basics/measuring/index.html"};
const cdcAdults: LibrarySource={label:"CDC — Adding Physical Activity as an Adult, 2025",url:"https://www.cdc.gov/physical-activity-basics/adding-adults/"};
const who: LibrarySource={label:"WHO — Physical Activity Recommendations",url:"https://www.who.int/europe/news-room/fact-sheets/item/physical-activity"};
export const libraryExpansion2026C: LibraryItem[]=[
{
  slug:"intensidade-do-cardio-sem-relogio",
  type:"article" as const,
  title:"Intensidade do cardio sem depender do relógio",
  eyebrow:"CARDIO & CONDICIONAMENTO",
  description:"Talk test e percepção de esforço ajudam a distinguir intensidade moderada e vigorosa mesmo sem monitor cardíaco.",
  readTime:"6 min",
  access:"PUBLIC" as const,
  tags:["cardio","intensidade","condicionamento"],
  updated:"2026-09-26",
  body:[{"heading":"Intensidade é relativa","paragraphs":["A mesma velocidade pode ser leve para uma pessoa e vigorosa para outra. Por isso, velocidade e inclinação ajudam, mas não substituem a percepção do esforço."]},{"heading":"Use o talk test","paragraphs":["O CDC usa uma regra simples: em intensidade moderada você normalmente consegue conversar, mas não cantar; em intensidade vigorosa, dizer mais do que poucas palavras sem pausar para respirar fica difícil."]},{"heading":"Escala de 0 a 10","paragraphs":["Outra referência prática é a percepção de esforço. Em termos relativos, esforço moderado costuma ficar por volta de 5–6/10 e vigoroso a partir de aproximadamente 7–8/10."]},{"heading":"O objetivo não é sofrer","paragraphs":["Nem toda sessão precisa ser vigorosa. Distribuir esforço ao longo da semana permite somar atividade sem transformar cada dia num teste máximo."]}],
  sources:[acsm,cdcIntensity,cdcAdults,who],
},
{
  slug:"forca-e-cardio-como-organizar",
  type:"article" as const,
  title:"Força e cardio: como organizar a semana",
  eyebrow:"PROGRAMAÇÃO",
  description:"As duas capacidades podem coexistir. A prioridade define onde colocar as sessões mais exigentes.",
  readTime:"6 min",
  access:"PUBLIC" as const,
  tags:["força","cardio","programação"],
  updated:"2026-09-26",
  body:[{"heading":"Não é uma escolha binária","paragraphs":["WHO e CDC recomendam atividade aeróbia e fortalecimento muscular para adultos. Um programa completo pode trabalhar ambos."]},{"heading":"Proteja a prioridade","paragraphs":["Se o principal objetivo é força, preserve qualidade nos treinos mais importantes e evite colocar condicionamento muito exigente imediatamente antes deles quando isso prejudica a execução."]},{"heading":"Use dias leves","paragraphs":["Caminhada, bicicleta confortável e outras opções moderadas podem aumentar movimento sem exigir a mesma recuperação de intervalos vigorosos."]},{"heading":"A semana é a unidade de decisão","paragraphs":["Observe energia, performance e aderência durante várias sessões. Se duas modalidades começam a competir, ajuste volume, intensidade ou distribuição antes de eliminar uma delas."]}],
  sources:[acsm,cdcIntensity,cdcAdults,who],
},
{
  slug:"ordem-dos-exercicios-sem-dogma",
  type:"article" as const,
  title:"Ordem dos exercícios sem dogma",
  eyebrow:"TREINO INTELIGENTE",
  description:"Coloque primeiro aquilo que precisa de mais atenção, técnica ou performance; o resto pode seguir a lógica da sessão.",
  readTime:"6 min",
  access:"PUBLIC" as const,
  tags:["programação","ordem","força"],
  updated:"2026-09-26",
  body:[{"heading":"Primeiro o que mais importa","paragraphs":["Quando um movimento ou capacidade é prioridade, fazê-lo cedo tende a permitir mais atenção e melhor performance."]},{"heading":"Complexidade também conta","paragraphs":["Movimentos mais técnicos costumam beneficiar de menor fadiga acumulada. Exercícios simples e acessórios são mais fáceis de mover para o final."]},{"heading":"Não existe uma sequência universal","paragraphs":["Para a maioria dos adultos saudáveis, consistência e volume apropriado têm mais peso do que regras rígidas de ordem."]},{"heading":"Quando mudar","paragraphs":["Se um exercício importante está sempre prejudicado porque chega tarde, experimente movê-lo. Use o registo das sessões para decidir."]}],
  sources:[acsm,cdcIntensity,cdcAdults,who],
},
{
  slug:"supersets-quando-fazem-sentido",
  type:"article" as const,
  title:"Supersets: quando fazem sentido",
  eyebrow:"EFICIÊNCIA",
  description:"Supersets podem economizar tempo, desde que não comprometam o trabalho que realmente precisa de qualidade.",
  readTime:"6 min",
  access:"PUBLIC" as const,
  tags:["supersets","tempo","força"],
  updated:"2026-09-26",
  body:[{"heading":"Superset é organização","paragraphs":["Executar dois exercícios alternadamente pode reduzir tempo total de sessão. Isso não torna automaticamente o treino melhor ou pior."]},{"heading":"Combine sem criar gargalo","paragraphs":["Movimentos que competem pouco entre si costumam funcionar melhor quando o objetivo é manter performance."]},{"heading":"Não comprima o principal","paragraphs":["Se um exercício pesado ou técnico perde qualidade porque o descanso ficou insuficiente, o superset deixou de ser uma solução eficiente."]},{"heading":"Use onde o custo é baixo","paragraphs":["Acessórios, core e combinações simples são bons candidatos. O objetivo é poupar tempo sem esconder fadiga."]}],
  sources:[acsm,cdcIntensity,cdcAdults,who],
},
{
  slug:"tempo-da-repeticao-sem-contar-cada-segundo",
  type:"article" as const,
  title:"Tempo da repetição sem contar cada segundo",
  eyebrow:"EXECUÇÃO",
  description:"Controle e intenção importam; contar 3-1-2 em toda repetição não é obrigatório para treinar bem.",
  readTime:"6 min",
  access:"PUBLIC" as const,
  tags:["técnica","tempo","execução"],
  updated:"2026-09-26",
  body:[{"heading":"Controle antes de cronómetro","paragraphs":["Uma repetição deve manter posição e trajetória compatíveis com o exercício. Isso pode ser ensinado sem transformar cada fase num metrónomo."]},{"heading":"Use tempo quando resolve algo","paragraphs":["Pausas e descidas mais controladas podem ajudar a aprender posições, aumentar consciência ou adaptar um exercício com pouca carga."]},{"heading":"Intenção também importa","paragraphs":["Em objetivos de potência, a intenção de mover rapidamente na fase concêntrica é diferente de deliberadamente tornar toda repetição lenta."]},{"heading":"A regra simples","paragraphs":["Controle o que precisa ser controlado e acelere apenas quando técnica e objetivo permitem."]}],
  sources:[acsm,cdcIntensity,cdcAdults,who],
},
{
  slug:"bilateral-ou-unilateral",
  type:"article" as const,
  title:"Bilateral ou unilateral?",
  eyebrow:"VARIAÇÕES",
  description:"Treinar com dois lados ou um lado de cada vez são ferramentas diferentes; nenhuma precisa vencer a outra.",
  readTime:"6 min",
  access:"PUBLIC" as const,
  tags:["unilateral","bilateral","variações"],
  updated:"2026-09-26",
  body:[{"heading":"Duas formas de organizar o desafio","paragraphs":["Agachamentos, remadas e presses podem ter versões bilaterais ou unilaterais. A escolha muda estabilidade, carga e tempo da sessão."]},{"heading":"Quando unilateral ajuda","paragraphs":["Pode ampliar opções com pouco equipamento, aumentar exigência de estabilidade e permitir trabalhar cada lado separadamente."]},{"heading":"Quando bilateral ajuda","paragraphs":["Pode ser mais simples de aprender em alguns movimentos, permitir maior carga total e reduzir o tempo de sessão."]},{"heading":"Escolha pelo problema","paragraphs":["Use a variação que melhor atende equipamento, objetivo, conforto e progressão. Não é necessário substituir uma família inteira pela outra."]}],
  sources:[acsm,cdcIntensity,cdcAdults,who],
},
{
  slug:"quando-aumentar-volume-de-treino",
  type:"article" as const,
  title:"Quando aumentar o volume do treino",
  eyebrow:"PROGRESSÃO",
  description:"Mais séries podem aumentar o estímulo, mas o próximo passo deve ser pequeno e tolerável.",
  readTime:"6 min",
  access:"PUBLIC" as const,
  tags:["volume","progressão","recuperação"],
  updated:"2026-09-26",
  body:[{"heading":"Volume é uma alavanca","paragraphs":["Adicionar séries aumenta trabalho total. Em alguns objetivos, mais volume pode ser útil, mas isso também aumenta tempo e recuperação necessários."]},{"heading":"Antes de aumentar","paragraphs":["Verifique se as séries atuais estão sendo cumpridas com execução consistente e esforço apropriado."]},{"heading":"Mude uma variável","paragraphs":["Adicionar uma série a poucos exercícios é mais fácil de avaliar do que aumentar séries, carga e frequência simultaneamente."]},{"heading":"Observe o padrão","paragraphs":["Se performance, sono, soreness e vontade de treinar pioram de forma consistente, talvez o volume esteja avançando mais rápido do que a capacidade de recuperação."]}],
  sources:[acsm,cdcIntensity,cdcAdults,who],
},
{
  slug:"uma-sessao-dificil-nao-e-uma-tendencia",
  type:"article" as const,
  title:"Uma sessão difícil não é uma tendência",
  eyebrow:"PROGRESS",
  description:"Dias ruins existem. Ajustes grandes pedem padrões repetidos, não uma única sessão fora do normal.",
  readTime:"6 min",
  access:"PUBLIC" as const,
  tags:["progress","autorregulação","consistência"],
  updated:"2026-09-26",
  body:[{"heading":"Ruído acontece","paragraphs":["Sono curto, alimentação, stress, calor, horário e muitos outros fatores podem alterar a sensação de uma sessão."]},{"heading":"Comece pelo menor ajuste","paragraphs":["Se o aquecimento parece pior, reduza a primeira carga, aumente descanso ou corte uma série antes de abandonar todo o treino."]},{"heading":"Registe contexto","paragraphs":["Uma nota curta ajuda a distinguir um dia isolado de um padrão que merece mudança."]},{"heading":"Procure repetição","paragraphs":["Quando a mesma queda aparece em várias sessões, aí existe mais informação para ajustar volume, intensidade ou recuperação."]}],
  sources:[acsm,cdcIntensity,cdcAdults,who],
},
{
  slug:"recuperacao-entre-treinos-sem-formula",
  type:"article" as const,
  title:"Recuperação entre treinos sem fórmula",
  eyebrow:"RECOVERY",
  description:"Recuperar não é esperar sentir-se perfeito; é chegar à próxima sessão com capacidade suficiente para executar o plano.",
  readTime:"6 min",
  access:"PUBLIC" as const,
  tags:["recovery","fadiga","sono"],
  updated:"2026-09-26",
  body:[{"heading":"Recuperação é capacidade de repetir","paragraphs":["A pergunta prática não é apenas se existe alguma soreness, mas se você consegue voltar a executar movimentos e esforço planejados com qualidade."]},{"heading":"Olhe o conjunto","paragraphs":["Sono, energia, stress, dor muscular, performance e aderência oferecem mais contexto quando observados em conjunto."]},{"heading":"Nem tudo exige descanso total","paragraphs":["Movimento leve, treino de outra capacidade ou uma sessão reduzida podem ser compatíveis com recuperação dependendo do contexto."]},{"heading":"Sinais fora do normal","paragraphs":["Dor aguda, perda relevante de função ou sintomas persistentes não devem ser normalizados como simples fadiga de treino."]}],
  sources:[acsm,cdcIntensity,cdcAdults,who],
},
{
  slug:"a-semana-minima-que-mantem-o-habito",
  type:"article" as const,
  title:"A semana mínima que mantém o hábito",
  eyebrow:"ADERÊNCIA",
  description:"Quando a rotina aperta, reduzir o plano é melhor do que abandonar o sistema inteiro.",
  readTime:"6 min",
  access:"PUBLIC" as const,
  tags:["hábitos","consistência","tempo"],
  updated:"2026-09-26",
  body:[{"heading":"Planeie a semana difícil","paragraphs":["Um programa robusto precisa de uma versão que funcione quando trabalho, viagens ou imprevistos reduzem disponibilidade."]},{"heading":"Mantenha âncoras","paragraphs":["Duas sessões curtas de força e movimento diário podem preservar a estrutura da rotina até a semana voltar ao normal."]},{"heading":"Reduza escopo","paragraphs":["Faça menos exercícios ou séries, mas mantenha os padrões principais em vez de comprimir tudo sem descanso."]},{"heading":"Volte sem compensar","paragraphs":["Não tente pagar sessões perdidas com uma sequência excessiva. Retome o calendário a partir do ponto atual."]}],
  sources:[acsm,cdcIntensity,cdcAdults,who],
},
{
  slug:"caminhar-conta-sim",
  type:"article" as const,
  title:"Caminhar conta? Sim.",
  eyebrow:"MOVIMENTO 360",
  description:"Caminhada pode contribuir para atividade aeróbia semanal e é uma ferramenta prática para aumentar movimento.",
  readTime:"6 min",
  access:"PUBLIC" as const,
  tags:["caminhada","cardio","atividade física"],
  updated:"2026-09-26",
  body:[{"heading":"Tudo depende da intensidade","paragraphs":["Uma caminhada confortável conta como movimento; uma caminhada rápida pode atingir intensidade moderada dependendo da pessoa."]},{"heading":"Use o talk test","paragraphs":["Quando consegue conversar mas cantar já fica difícil, a atividade costuma estar numa faixa moderada relativa."]},{"heading":"É fácil de distribuir","paragraphs":["Caminhadas podem ser divididas ao longo da semana e encaixadas em deslocamentos, pausas e lazer."]},{"heading":"Não substitui tudo","paragraphs":["Força continua sendo uma capacidade separada. Uma rotina completa combina movimento aeróbio com fortalecimento muscular."]}],
  sources:[acsm,cdcIntensity,cdcAdults,who],
},
{
  slug:"mais-movimento-no-dia-de-trabalho",
  type:"article" as const,
  title:"Mais movimento num dia de trabalho",
  eyebrow:"HÁBITOS",
  description:"Pequenas oportunidades de movimento reduzem a dependência de uma única sessão perfeita para tornar o dia ativo.",
  readTime:"6 min",
  access:"PUBLIC" as const,
  tags:["hábitos","movimento","trabalho"],
  updated:"2026-09-26",
  body:[{"heading":"Não espere apenas pelo treino","paragraphs":["Atividade física inclui deslocamentos, caminhadas, tarefas e lazer. O treino é uma parte importante, mas não a única."]},{"heading":"Crie gatilhos simples","paragraphs":["Levantar entre blocos de trabalho, caminhar em chamadas e escolher percursos ativos quando possível são formas de adicionar movimento sem uma segunda rotina complexa."]},{"heading":"Não precisa medir tudo","paragraphs":["Passos podem ajudar algumas pessoas, mas não são obrigatórios para que uma pausa ativa tenha valor."]},{"heading":"O sistema deve caber no trabalho","paragraphs":["Escolha ações que não dependam de motivação excepcional. Repetibilidade é mais importante do que criar um protocolo perfeito de pausas."]}],
  sources:[acsm,cdcIntensity,cdcAdults,who],
}
];
